
import { Metadata } from "next";
import { Header } from "@/components/layout/header"
import { Sidebar } from "@/components/layout/sidebar"

export const metadata: Metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};



export default function HomeLayout({ children }: { children: React.ReactNode }) {

    return (
        <>

            <Header />

            <div className="flex">
                {/* Desktop Sidebar */}
                <aside className="hidden lg:block w-64 h-[calc(100vh-4rem)] sticky top-16">
                    <Sidebar />
                </aside>

                {/* Main Content */}
                <main className="flex-1 p-6 lg:p-8">
                    <div className="max-w-7xl mx-auto">{children}</div>
                </main>
            </div>
        </>
    )

}